### ISSUE TITLE
Portal da transparencia

### ISSUE THREAD

**Issue by hermesalvesbr** [adsonvinicius/sagres-pca#1]
Bom dia, 

Estou precisando fazer um front para um arquivo sagres contábil, tem interesse em conversar sobre isto? #freelancer

**Comment by adsonvinicius** [comment]
Bom dia, podemos sim, basta acrescentar o gmail no username do profile aqui do github.

**Comment by hermesalvesbr** [comment]
Te mandei email do meu gmail.
